AIRPORTS = [
    {"code": "RUH", "city": "Riyadh", "city_ar": "الرياض", "country_ar": "السعودية"},
    {"code": "JED", "city": "Jeddah", "city_ar": "جدة", "country_ar": "السعودية"},
    {"code": "MED", "city": "Madinah", "city_ar": "المدينة المنورة", "country_ar": "السعودية"},
    {"code": "DMM", "city": "Dammam", "city_ar": "الدمام", "country_ar": "السعودية"},
    {"code": "AHB", "city": "Abha", "city_ar": "أبها", "country_ar": "السعودية"},
    {"code": "TUU", "city": "Tabuk", "city_ar": "تبوك", "country_ar": "السعودية"},
    {"code": "DXB", "city": "Dubai", "city_ar": "دبي", "country_ar": "الإمارات"},
    {"code": "AUH", "city": "Abu Dhabi", "city_ar": "أبوظبي", "country_ar": "الإمارات"},
    {"code": "DOH", "city": "Doha", "city_ar": "الدوحة", "country_ar": "قطر"},
    {"code": "CAI", "city": "Cairo", "city_ar": "القاهرة", "country_ar": "مصر"},
    {"code": "IST", "city": "Istanbul", "city_ar": "إسطنبول", "country_ar": "تركيا"},
    {"code": "LHR", "city": "London", "city_ar": "لندن", "country_ar": "بريطانيا"},
    {"code": "CDG", "city": "Paris", "city_ar": "باريس", "country_ar": "فرنسا"},
    {"code": "KUL", "city": "Kuala Lumpur", "city_ar": "كوالالمبور", "country_ar": "ماليزيا"},
    {"code": "BKK", "city": "Bangkok", "city_ar": "بانكوك", "country_ar": "تايلاند"},
    {"code": "JFK", "city": "New York", "city_ar": "نيويورك", "country_ar": "أمريكا"},
    {"code": "GVA", "city": "Geneva", "city_ar": "جنيف", "country_ar": "سويسرا"},
    {"code": "BEY", "city": "Beirut", "city_ar": "بيروت", "country_ar": "لبنان"},
    {"code": "AMM", "city": "Amman", "city_ar": "عمّان", "country_ar": "الأردن"},
    {"code": "TUN", "city": "Tunis", "city_ar": "تونس", "country_ar": "تونس"},
]
